export const FETCH_POSTS_BEGIN = "FETCH_POSTS_BEGIN";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAIL = "FETCH_POSTS_FAIL";
export const SAVE_SUBREDDIT = "SAVE_SUBREDDIT";
export const SAVE_POSTS_TO_LOAD = "SAVE_POSTS_TO_LOAD";


export const SAVE_POST_TO_STORAGE = "SAVE_POST_TO_STORAGE";
export const DELETE_POST_FROM_STORAGE = "DELETE_POST_FROM_STORAGE";
