export const FETCH_POSTS_BEGIN = "FETCH_POSTS_BEGIN";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAIL = "FETCH_POSTS_FAIL";
export const SAVE_SUBREDDIT = "SAVE_SUBREDDIT";
export const SAVE_POSTS_TO_LOAD = "SAVE_POSTS_TO_LOAD";


export const SAVE_POST_TO_STORAGE = "SAVE_POST_TO_STORAGE";
export const DELETE_POST_FROM_STORAGE = "DELETE_POST_FROM_STORAGE";


export const USER_LOGIN_BEGIN = 'USER_LOGIN_BEGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = "USER_LOGOUT";
export const GET_USER_GROUPS = "GET_USER_GROUPS";
export const SET_CURRENT_GROUP = "SET_CURRENT_GROUP";
export const GET_PHOTO_SERVER_URL='GET_PHOTO_SERVER_URL';
export const GET_DOCS_SERVER_URL='GET_DOCS_SERVER_URL';
